/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yazlabproje1;

import java.awt.*;
import java.io.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.StringTokenizer;
import net.sourceforge.tess4j.*;
import javax.swing.*;
import javax.swing.filechooser.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.opencv.core.*;
import static org.opencv.imgcodecs.Imgcodecs.imread;

/**
 *
 * @author HARUN
 */
public class Form extends javax.swing.JFrame {

    JFrame jframe;
    Connection vtbaglanti = null;
    String jdbc = "jdbc:mysql://localhost:3307/veritabanim?zeroDateTimeBehavior=convertToNull";
    String kullanici = "root";
    String sifre = "";
    //DBQueryProcessor islem;
    Object[][] update;

    /**
     * Creates new form Form
     */
    public void tabloGuncelle() {
        //update=process.

    }

    public ImageIcon ResimDondur(String DosyaYolu) {
        ImageIcon fotoicon = new ImageIcon(DosyaYolu);
        Image foto = fotoicon.getImage();
        Image yenifoto = foto.getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img = new ImageIcon(yenifoto);
        return img;
    }

    public Form() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fiş Okuma Programı");
        setResizable(false);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HARUN\\Desktop\\yazlabproje1\\testphotos\\parseicon.png")); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setText("Arama");

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        jLabel2.setText("İşletme Adı: ");

        jLabel3.setText("Tarih: ");

        jSeparator1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel4.setText("Tüm Bilgiler");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "İşletme Adı", "Tarih", "Fiş No", "KDV", "Toplam Tutar", "Ürün Adı", "Ürün KDV", "Ürün Fiyatı"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jButton1.setText("Bağlantı Testi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Verileri Çek");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setText(" ");

        jLabel7.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(107, 107, 107)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String dizi[][] = new String[50][150];
        int i = 0;
        JFileChooser dosyasecici = new JFileChooser();
        dosyasecici.setCurrentDirectory(new File("C:\\Users\\HARUN\\Desktop\\yazlabproje1\\testphotos\\fislerim"));
        dosyasecici.setDialogTitle("Lutfen fişinizi seçiniz...");
        //dosyasecici.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filtre = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png", "pdf");
        dosyasecici.addChoosableFileFilter(filtre);
        int sonuc = dosyasecici.showOpenDialog(null);

        if (sonuc == JFileChooser.APPROVE_OPTION) {
            File secilendosya = dosyasecici.getSelectedFile();
            String dosyayolu = secilendosya.getAbsolutePath();
            jLabel5.setIcon(ResimDondur(dosyayolu));
            System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
            Mat resim = imread(dosyayolu);
            File imgyolu = new File(dosyayolu);
            ITesseract ts = new Tesseract();
            ts.setDatapath("C:\\Users\\HARUN\\Downloads\\Compressed\\Tess4J\\tessdata");
            //System.out.println(imgyolu.canRead());
            ts.setLanguage("tur");

            try {
                vtbaglanti = DriverManager.getConnection(jdbc, kullanici, sifre);
                Statement st = vtbaglanti.createStatement();
                String fotoyazi = ts.doOCR(imgyolu);
                jTextArea2.setText(fotoyazi);
                jLabel6.setText("Okundu");
                StringTokenizer token = new StringTokenizer(fotoyazi);
                while (token.hasMoreTokens()) {
                    dizi[25][i] = token.nextToken();
                    //System.out.println(dizi[25][i]);
                    i++;
                }
                String v = ", ";
                String isletmeadi = dizi[25][0];
                String fistarihi = dizi[25][1];
                String fisno = dizi[25][2];
                String fiskdv = dizi[25][3];
                String fistoplami = dizi[25][4];
                String urunadi = dizi[25][5];
                String urunadi2 = dizi[25][6];
                String urunadi3 = dizi[25][7];
                String urunkdv = dizi[25][10];
                String urunkdv2 = dizi[25][11];
                String urunkdv3 = dizi[25][12];
                String urunfiyat = dizi[25][15];
                String urunfiyat2 = dizi[25][16];
                String urunfiyat3 = dizi[25][17];

                int k = i;
                int temp = 0;
                int temp2 = 0;
                for (i = 0; i < k; i++) {

                    if (dizi[25][i].equalsIgnoreCase("Bim") && dizi[25][i + 1].equalsIgnoreCase("Mağazaları")) {
                        temp = i;
                        temp2 = i + 1;
                        isletmeadi = dizi[25][temp] + " " + dizi[25][temp2];
                        temp = 12;

                        urunadi = dizi[25][temp] + " " + dizi[25][temp + 1];
                        urunkdv = dizi[25][temp + 2];
                        urunfiyat = dizi[25][temp + 3];
                        temp = 16;

                        urunadi2 = dizi[25][temp];
                        urunkdv2 = dizi[25][temp + 1];
                        urunfiyat2 = dizi[25][temp + 2];
                        temp = 19;

                        urunadi3 = dizi[25][temp];
                        urunkdv3 = dizi[25][temp + 1];
                        urunfiyat3 = dizi[25][temp + 2];

                    }
                    if (dizi[25][i].equalsIgnoreCase("A101")) {
                        temp = i;
                        isletmeadi = dizi[25][temp];
                        temp = 11;

                        urunadi = dizi[25][temp] + " " + dizi[25][temp + 1];
                        urunkdv = dizi[25][temp + 2];
                        urunfiyat = dizi[25][temp + 3];
                        temp = 15;

                        urunadi2 = dizi[25][temp];
                        urunkdv2 = dizi[25][temp + 1];
                        urunfiyat2 = dizi[25][temp + 2];
                        temp = 18;

                        urunadi3 = dizi[25][temp] + " " + dizi[25][temp + 1];
                        urunkdv3 = dizi[25][temp + 2];
                        urunfiyat3 = dizi[25][temp + 3];

                    }
                    
                    if (dizi[25][i].equalsIgnoreCase("Migros")) {
                        temp = i;
                        isletmeadi = dizi[25][temp];
                        temp = 11;

                        urunadi = dizi[25][temp] + " " + dizi[25][temp + 1];
                        urunkdv = dizi[25][temp + 2];
                        urunfiyat = dizi[25][temp + 3];
                        temp = 15;

                        urunadi2 = dizi[25][temp] + " " + dizi[25][temp + 1];
                        urunkdv2 = dizi[25][temp + 2];
                        urunfiyat2 = dizi[25][temp + 3];
                        temp = 19;

                        urunadi3 = dizi[25][temp] + " " + dizi[25][temp + 1];
                        urunkdv3 = dizi[25][temp + 2];
                        urunfiyat3 = dizi[25][temp + 3];

                    }
                    
                    if (dizi[25][i].equalsIgnoreCase("KARDEŞLER")&& dizi[25][i+1].equalsIgnoreCase("AYAKKABI")) {
                        temp = i;
                        isletmeadi = dizi[25][temp] + " " + dizi[25][temp+1];
                        temp = 12;

                        urunadi = dizi[25][temp] + " " + dizi[25][temp + 1] + " " + dizi[25][temp + 2];
                        urunkdv = dizi[25][temp + 3];
                        urunfiyat = dizi[25][temp + 4];
                        temp = 17;

                        urunadi2 = dizi[25][temp] + " " + dizi[25][temp + 1];
                        urunkdv2 = dizi[25][temp + 2];
                        urunfiyat2 = dizi[25][temp + 3];
                        temp = 21;

                        urunadi3 = dizi[25][temp] + " " + dizi[25][temp + 1];
                        urunkdv3 = dizi[25][temp + 2];
                        urunfiyat3 = dizi[25][temp + 3];

                    }
                    
                    
                    if (dizi[25][i].equalsIgnoreCase("Tarih:")) {
                        temp = i + 1;
                        fistarihi = dizi[25][temp];
                    }

                    if (dizi[25][i].equalsIgnoreCase("No:")) {
                        temp = i + 1;
                        fisno = dizi[25][temp];
                    }

                    if (dizi[25][i].equalsIgnoreCase("KDV:")) {
                        temp = i + 1;
                        fiskdv = dizi[25][temp];
                    }
                    if (dizi[25][i].equalsIgnoreCase("Toplam:")) {
                        temp = i + 1;
                        fistoplami = dizi[25][temp];
                    }

                }
                System.out.println("İşletme Adı: " + isletmeadi);
                System.out.println("Fiş Tarihi: " + fistarihi);
                System.out.println("Fiş No: " + fisno);
                System.out.println("1.Urun Adı: " + urunadi);
                System.out.println(urunadi + " KDV: " + urunkdv);
                System.out.println(urunadi + " Fiyati: " + urunfiyat);
                System.out.println("2.Urun Adı: " + urunadi2);
                System.out.println(urunadi2 + " KDV: " + urunkdv2);
                System.out.println(urunadi2 + " Fiyati: " + urunfiyat2);
                System.out.println("3.Urun Adı: " + urunadi3);
                System.out.println(urunadi3 + " KDV: " + urunkdv3);
                System.out.println(urunadi3 + " Fiyati: " + urunfiyat3);
                System.out.println("Fiş Toplam KDV: " + fiskdv);
                System.out.println("Fiş Genel Toplam: " + fistoplami);
                String marketAdi = "";

                if ("BİM MAĞAZALARI".equals(isletmeadi)) {
                    marketAdi = "Bim Mağazaları";
                }
                if ("A101".equals(isletmeadi)) {
                    marketAdi = "A101";
                }
                if ("MİGROS".equals(isletmeadi)) {
                    marketAdi = "Migros";
                }
                if ("KARDEŞLER AYAKKABI".equals(isletmeadi)) {
                    marketAdi = "Kardeşler Ayakkabı";
                }

                String ekleme = "insert into fisler(marketAdi,fisTarih,fisNo,fisKDV,fisToplam) values('" + marketAdi + "','" + fistarihi + "','" + fisno + "','" + fiskdv + "','" + fistoplami + "')";
                st.executeUpdate(ekleme);
                String sqlMarketId = "select marketID from fisler where marketAdi='"+marketAdi+"' ORDER BY marketId DESC LIMIT 1";
                ResultSet rsMarketId = st.executeQuery(sqlMarketId);
                int marketId = 0;
                while (rsMarketId.next()) {
                    marketId = rsMarketId.getInt("marketID");
                    break;
                }

                if (marketId > 0) {
                    String ekleme2 = "insert into urunler(urunAdi,urunKDV,urunFiyat,urunmarketID) values('"+urunadi+"','"+urunkdv+"','"+urunfiyat+"'," + marketId + ")";
                    st.executeUpdate(ekleme2);
                    String ekleme3 = "insert into urunler(urunAdi,urunKDV,urunFiyat,urunmarketID) values('"+urunadi2+"','"+urunkdv2+"','"+urunfiyat2+"'," + marketId + ")";
                    st.executeUpdate(ekleme3);
                    String ekleme4 = "insert into urunler(urunAdi,urunKDV,urunFiyat,urunmarketID) values('"+urunadi3+"','"+urunkdv3+"','" +urunfiyat3+"'," + marketId + ")";
                    st.executeUpdate(ekleme4);
                }
                jLabel7.setText("Aktarıldı");
                vtbaglanti.close();

                //System.out.println(dizi[15][5]);
                //fotoyazi.equalsIgnoreCase(fotoyazi);
            } catch (Exception e) {
                System.err.println(e.getMessage());
            }

            //jTextArea2.setColumns;
            //imshow("deneme",resim);
            //waitKey(1);
            //destroyAllWindows(); 
        } else {
            JOptionPane.showMessageDialog(jframe, "Dosya seçme işlemi iptal edildi!", "İptal", 0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            Class.forName("com.mysql.jdbc.Driver");
            vtbaglanti = DriverManager.getConnection(jdbc, kullanici, sifre);
            if (vtbaglanti != null) {
                JOptionPane.showMessageDialog(jframe, "Veritabanına baglanti saglandi!", "Baglanti Testi", 1);
            }
            vtbaglanti.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jframe, "Veritabanına baglanti saglanilamadi!", "Baglanti Testi", 0);
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        try {
            vtbaglanti = DriverManager.getConnection(jdbc, kullanici, sifre);
            Statement st = vtbaglanti.createStatement();
            ResultSet rs = st.executeQuery("Select * from fisler inner join urunler on fisler.marketID=urunler.urunmarketID");
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Object[] sutun = {rs.getString("marketAdi"), rs.getString("fisTarih"), rs.getString("fisNo"), rs.getString("fisKDV"), rs.getString("fisToplam"), rs.getString("urunAdi"), rs.getString("urunKDV"), rs.getString("urunFiyat")};
                model.addRow(sutun);
            }
            JOptionPane.showMessageDialog(jframe, "Veriler aktarıldı!", "Aktarma", 1);
            vtbaglanti.close();
            }
            catch (Exception e) {
            JOptionPane.showMessageDialog(jframe, "Tablo veritabanından aktarılamadı!", "Aktarma", 0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
        try{
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            vtbaglanti = DriverManager.getConnection(jdbc, kullanici, sifre);
            Statement st = vtbaglanti.createStatement();
            ResultSet rs = st.executeQuery("Select * from fisler inner join urunler on fisler.marketID=urunler.urunmarketID where marketAdi like '" + jTextField2.getText() + "%'");
            model.setRowCount(0);
            while(rs.next()){
                Object[] sutun = {rs.getString("marketAdi"), rs.getString("fisTarih"), rs.getString("fisNo"), rs.getString("fisKDV"), rs.getString("fisToplam"), rs.getString("urunAdi"), rs.getString("urunKDV"), rs.getString("urunFiyat")};
                model.addRow(sutun);
            
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(jframe, "Arama işlemi yapılamadı!", "Arama", 0);
        
        }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
        try{
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            vtbaglanti = DriverManager.getConnection(jdbc, kullanici, sifre);
            Statement st = vtbaglanti.createStatement();
            ResultSet rs = st.executeQuery("Select * from fisler inner join urunler on fisler.marketID=urunler.urunmarketID where fisTarih like '" + jTextField3.getText() + "%'");
            model.setRowCount(0);
            while(rs.next()){
                Object[] sutun = {rs.getString("marketAdi"), rs.getString("fisTarih"), rs.getString("fisNo"), rs.getString("fisKDV"), rs.getString("fisToplam"), rs.getString("urunAdi"), rs.getString("urunKDV"), rs.getString("urunFiyat")};
                model.addRow(sutun);
            
            }
        
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(jframe, "Arama işlemi yapılamadı!", "Arama", 0);
        
        }
    }//GEN-LAST:event_jTextField3KeyReleased

        

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });

        //Mat mat = Mat.eye(3, 3, CvType.CV_8UC1);
        //System.out.println("mat = " + mat.dump());
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
